### ISSUE TITLE
Use this theme for peppy?

### ISSUE THREAD

**Issue by vreuter** [databio/mkdocs-databio#5]
@nsheff is this intended to be used for `peppy` docs? Will `pepkit` have its own theme, use one of the standard ones, or decide on docs themes at the repo level rather than org level?

**Comment by nsheff** [comment]
Ok I've just made a release, of version `0.1`. it's relatively stable, we've used it successfully for:

- http://code.databio.org/caravel
- http://code.databio.org/divvy
- http://code.databio.org/episb
- http://code.databio.org/AIList
- http://code.databio.org/PEPATAC
