### ISSUE TITLE
Sidebar - navbar conflict in a narrow window

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/mkdocs-databio#6]
Not sure if this is something that can be fixed, but when the browser window is of low width (or the page is displayed on mobile devices) the depicted conflict emerges and there's no way to navigate the website:

<img width="662" alt="screen shot 2019-01-14 at 9 13 19 pm" src="https://user-images.githubusercontent.com/22797900/51154500-eecf1380-1841-11e9-9135-e4df61c92a97.png">

**Comment by nsheff** [comment]
yeah. that should be fixable. I just have to learn a little more boostrap...
